#! /bin/sh
dunst &
picom &
redshift &
sxhkd &
setxkbmap se
xsetroot -cursor_name left_ptr
xset r rate 200 40
xset m 0 0


if [ "$HOSTNAME" = "barbar" ]; then
    INTERNAL_MONITOR="eDP-1"
    EXTERNAL_MONITOR="DP-1"
    # on first load setup default workspaces
    if [[ "$1" = 0 ]]; then
	    if [[ $(xrandr -q | grep "^${EXTERNAL_MONITOR} connected") ]]; then
		    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
		    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
		    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	    else
		    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
	    fi
    fi
    ~/.local/bin/bspwm_setup_monitors.sh &
else
    bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10
    xrandr --output DP-2 --mode 3440x1440 --rate 160 --primary
    xset -dpms
    xwallpaper --zoom ~/.config/wall.jpg
    ~/.config/polybar/launch.sh
fi

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		27 

bspc config split_ratio          0.51
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#30302f"
bspc config active_border_color "#30302f"
bspc config presel_feedback_color "#30302f"

bspc rule -a \* rectangle 1600x1200+0+0 center=true

bspc rule -a discord desktop='^2'
bspc rule -a spotify desktop='^2'
