#! /bin/sh
dunst &
picom &
redshift &
sxhkd &
setxkbmap se,en
xsetroot -cursor_name left_ptr
xset r rate 200 40
xset m 0 0
xwallpaper --zoom ~/.config/wall.jpg
~/.config/polybar/launch.sh

if [ "$HOSTNAME" = "barbar" ]; then
    bspc monitor edp1 -d I II III IV V
    bspc monitor DP-1 -d VI VII VIII IX X
else
    bspc monitor DP-2 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		27 

bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config focused_border_color "#928374"

bspc rule -a \* rectangle 1600x1200+0+0 center=true

bspc rule -a discord desktop='^2'
bspc rule -a spotify desktop='^2'

# Fix for shadows in monocle mode
bspc subscribe desktop_layout | while read -r Event
do
  Desktop=$(echo "$Event" | awk '{print $3}')
  State=$(echo "$Event" | awk '{print $4}')
  if [ "$State" = "monocle" ]; then 
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -f _BSPWM_MONOCLE 32c -set _BSPWM_MONOCLE 1
    done
  elif [ $(bspc config window_gap) -gt 0 ]; then
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -remove _BSPWM_MONOCLE
    done
  fi
done &
